### PR TITLE
#1388 Include frontend service in the sample Python SDK test

### PR DESCRIPTION
**Pull request by jmsktm**
### Use Case: 1
```
Original Flow:
---> [Svc-A] ---> [[sidecar] Svc-B]


Preview Flow:
---> [Svc-A] ---> [[sidecar] ... ]
                      \
                       *---> [forkOf Svc-B]
```

```
$ SIGNADOT_API_KEY=<signadot_api_key> ROUTE_IMAGE=signadot/hotrod-route:540fadfd2fe619e20b794d56ce404761ce2b45a3 python3 tests/integration/usecase1_test.py

Frontend Service endpoint URL: https://hotrod-frontend--test-ws-v5wcp.preview.signadot.com
Checking workspace readiness
Attempt: 1/10
Attempt: 2/10
Workspace is ready!
.
----------------------------------------------------------------------
Ran 1 test in 5.482s

OK
```

### Use Case: 2
```
Original Flow:
------> [Svc-A] ------> [[sidecar] Svc-B]


Preview Flow:
                      *---> [[sidecar] ... ]
                     /         \
---> [forkOf Svc-A] *           *---> [forkOf Svc-B]
```

```
$ SIGNADOT_API_KEY=<signadot_api_key> ROUTE_IMAGE=signadot/hotrod-route:540fadfd2fe619e20b794d56ce404761ce2b45a3 FRONTEND_IMAGE=signadot/hotrod-frontend:5069b62ddc2625244c8504c3bca6602650494879 python3 tests/integration/usecase2_test.py

Frontend Service endpoint URL: https://hotrod-frontend--test-ws-mqqvm.preview.signadot.com
Checking workspace readiness
Attempt: 1/10
Attempt: 2/10
Attempt: 3/10
Attempt: 4/10
Workspace is ready!
.
----------------------------------------------------------------------
Ran 1 test in 15.395s

OK
```

### CODE REVIEW

**Comment by foxish** [comment]
I think the point of this one was to show an example of ad hoc workspace construction and not an integration test IIUC. cc @arjun-sd

**Comment by jmsktm** [comment]
Not sure about the reason for [#1388](https://github.com/signadot/signadot/issues/1388), but it's not really an integration test as well. Just creating a workspace using two forks, and testing the route service alone and printing out the frontend service endpoint url. So I don't know if the example serves more value than just creating a single workspace.

**Comment by arjun-sd** [comment]
@jmsktm I've provided some more context in #1388

**Comment by jmsktm** [comment]
@arjun-sd: In this PR, I have updated the single-service test to include frontend as well. So the single-service use case (#1) no longer exists. Would you recommend two test files in that case?

Does the test/output for use case #2 look good to you?
https://github.com/signadot/examples/pull/9#issue-1126297808

**Comment by jmsktm** [comment]
Alternately, if we are to go by Anirudh's suggestion, we could keep the current repo to just demonstrate workspace creation (as we have in the other two repositories, thereby maintaining consistency as well), and just share sample codes to ShareChat for their specific need - maybe in just a separate branch?

**Comment by jmsktm** [comment]
@arjun-sd: I have updated the PR as per the huddle this morning.

**Comment by arjun-sd** [comment]
+1 for the fantastic documentation within these examples @jmsktm !!

**Comment by jmsktm** [comment]
Thoughts on this, @arjun-sd, @foxish? The original test file is unchanged, and I have added two new test files for the two new use cases.

**Comment by arjun-sd** [comment]
Looks good @jmsktm. This should suffice. Can you merge it so I can share with ShareChat? Thx

**Comment by jmsktm** [comment]
done

**Pull request merged**
